# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 10.15.3
        uses: actions/setup-node@v3
        with:
          node-version: "10.15.3"
          cache: "npm"
      - run: npm ci
      - name: Install builder-webpack Dependencies
        run: |
          echo $(pwd -P)
          npm ci
        working-directory: ./builder-webpack
      - name: Install builder-webpack Dependencies
        run: npm run test
        working-directory: ./builder-webpack
